# Install only what is needed in the master nodes
- name: Install kubectl to the master nodes
  apt:
    name: kubectl
    state: present

- name: Install helm repository
  apt_repository:
        repo: deb https://charts.helm.sh/stable/debian/ stable main
        state: present

- name: Install Helm package
  apt:
      name: helm
      state: present
