# Install only what is needed in the master nodes
- name: Install kubectl to the master nodes
  apt:
    name: kubectl
    state: present

- name: Download Balto GPG key
  command: curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
  register: download_gpg_key

- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present